# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  basic_auth_name: <%= ENV["BASIC_AUTH_NAME"] %>
  basic_auth_password: <%= ENV["BASIC_AUTH_PASSWORD"] %>

development:
  <<: *common
  secret_key_base: c140bd37e9fa9fd489d36193aebe862282a42e94fca3573b8e01a0877d29225f5b039bf9812e0942fd267d294fb148110a6b4881e15dd7012e18769ab94f4b55

test:
  <<: *common
  secret_key_base: ee5af36d6621efd4fe11425da1c1bad37864fe6902b0273a93c658850eb1e371be361a8c63ba88fac9d19a98af4c308dc3f759241feeb3d1bc46566caa520da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
